Repository puppetlabs/puppetlabs-package, pull requests merged in 2019-12, with the labels that each got.

#164 pdksync - FM-8499 remove ubuntu 14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#165 (maint) - v1.0.0 Mergeback
  CHANGELOG.md
  metadata.json
Labels: maintenance

#168 pdksync - "MODULES-10236 disable deploy_to_forge for the module"
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#167 pdksync - "MODULES-10242 Add ubuntu14 support back to the modules"
  metadata.json
  provision.yaml
Labels: feature

#170 (maint) - v1.1.0 Merge Back
  CHANGELOG.md
  metadata.json
Labels: maintenance

#171 pdksync - (maint) travis updates: bundler and slack
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#173 pdksync - FM-8834 - Add GitHub action workflow
  .github/workflows/release.yml
Labels: maintenance
