Repository puppetlabs/puppetlabs-package, pull requests merged in 2019-03, with the labels that each got.

#113 (MODULES-8717) Fix for boltspec run dependancy issue
  spec/acceptance/init_spec.rb
  spec/acceptance/linux_spec.rb
  spec/acceptance/windows_spec.rb
  spec/spec_helper_acceptance.rb
Labels: bugfix

#114 pdksync - Remove .project from .gitignore
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .sync.yml
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#118 (SEN-795) Add discovery extension metadata
  tasks/linux.json
  tasks/windows.json
Labels: feature

#119 (SEN-795) Move extension metadata to init.json
  tasks/init.json
  tasks/linux.json
  tasks/windows.json
Labels: feature
