Repository puppetlabs/puppetlabs-package, pull requests merged in 2021-02, with the labels that each got.

#233 pdksync - Update gha templates
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .rubocop.yml
  .travis.yml
  Rakefile
  metadata.json
Labels: maintenance

#235 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .rubocop.yml
  .sync.yml
  .travis.yml
  appveyor.yml
  metadata.json
Labels: backwards-incompatible

#237 Fix package task for yum when passing version
  tasks/linux.sh
Labels: bugfix

#240 pdksync - (MAINT) Remove RHEL 5 family support
  metadata.json
Labels: maintenance

#241 pdksync - (MAINT) PDK update for GHA workflows + Litmus updates
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  metadata.json
Labels: maintenance
