Repository puppetlabs/puppetlabs-package, pull requests merged in 2022-10, with the labels that each got.

#289 pdksync - (CONT-130) - Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#291 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  Gemfile
  metadata.json
Labels: maintenance, hacktoberfest

#292 pdksync - (CONT-189) Remove support for RedHat6 / OracleLinux6
  metadata.json
Labels: bugfix, hacktoberfest

#293 (MAINT) Remove references to beaker
  README.md
Labels: maintenance
