Repository puppetlabs/puppetlabs-package, pull requests merged in 2022-03, with the labels that each got.

#275 pdksync - (FM-8922) - Add Support for Windows 2022
  metadata.json
Labels: feature

#276 pdksync - pdksync_heads/main-0-gf3911d3
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .github/workflows/spec.yml
  .rubocop.yml
  Gemfile
  Rakefile
  metadata.json
Labels: maintenance

#277 pdksync - (GH-iac-334) Remove Support for Ubuntu 14.04/16.04
  metadata.json
Labels: bugfix

#278 pdksync - Add labeller and stale GHA workflows
  .github/workflows/labeller.yml
  .github/workflows/stale.yml
Labels: maintenance
