Repository puppetlabs/puppetlabs-package, pull requests merged in 2023-04, with the labels that each got.

#300 pdksync - (CONT-844) - Update .sync.yml
  .sync.yml
Labels: maintenance

#305 Fix shebangs
  files/apt.sh
  files/common.sh
  files/yum.sh
  files/zypper.sh
  tasks/linux.sh
Labels: bugfix, community

#306 Add Compatibility with FreeBSD
  files/pkg.sh
  tasks/init.json
  tasks/linux.sh
Labels: feature, community

#307 (CONT-791) - Add Puppet 8/Drop Puppet 6
  .devcontainer/devcontainer.json
  .fixtures.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  metadata.json
  spec/acceptance/init_spec.rb
  spec/acceptance/windows_spec.rb
  spec/spec_helper.rb
  tasks/init.rb
Labels: backwards-incompatible
